name: CI/CD Django, Postgres

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecommerce
          ports: "5432:5432"
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Tests
        env:
          DJANGO_SECRET_KEY: CI_CD_TEST_KEY
          POSTGRES_DB: ecommerce
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          DEBUG: "0"
        run: |
          pytest